version: '2'

services:
  shiny:
    restart: always
    image: linards/shiny-server:latest
    expose:
      - 3838
    volumes:
      - ./appdir:/srv/shiny-server
      - ./logs:/var/log/shiny-server
    user: 'shiny'
    environment:
      - VIRTUAL_HOST=${SHINY_HOST}
      - LETSENCRYPT_HOST=${SHINY_HOST}
      - LETSENCRYPT_EMAIL=${SHINY_ADMIN}


networks:
  default:
    external:
      name: nginx-proxy
